### PR TITLE
Adding stdin reject if cli flags are provided

### PR DESCRIPTION
**Pull request by Mzack9999**

### CODE REVIEW

**Review by ehsandeep — CHANGES_REQUESTED** [review]
```go
go build 

# github.com/projectdiscovery/shuffledns/pkg/runner
../../pkg/runner/options.go:82:18: undefined: io.Discard
```

**Review by ehsandeep — CHANGES_REQUESTED** [review]
still getting the same error:-

```
$ git branch
* 35-bugfix-stdin-reject-with-cli-flags
  master

$ go build

$ echo "" | ./shuffledns -list u.txt -r r.txt -d uber.com

       __        ________        __       
  ___ / /  __ __/ _/ _/ /__  ___/ /__ ___
 (_-</ _ \/ // / _/ _/ / -_)/ _  / _ \(_-<
/___/_//_/\_,_/_//_//_/\__/ \_,_/_//_/___/ v1								

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[ERR] Could not run massdns: blank input file specified
[INF] Finished resolving. Hack the Planet!
```

**Comment by Mzack9999** [comment]
This is fixed. The correct CLI is:

```
echo "" | ./shuffledns -list u.txt -r r.txt -d uber.com -w w.txt
```

`-w` is missing

**Comment by ehsandeep** [comment]
Right, this is fixed, indeed I used the wrong flag 😄

**Pull request merged**
